# Generated by Django 2.0.2 on 2018-03-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbError', models.CharField(max_length=500)),
                ('dbErrorTime', models.DateTimeField(auto_now_add=True)),
                ('dbErrorCode', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbPacket', models.CharField(max_length=500)),
                ('dbTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
