# Generated by Django 2.0.2 on 2018-03-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogDataMonit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbLogTime', models.DateTimeField(auto_now_add=True)),
                ('dbTrafficState', models.IntegerField(default=0)),
                ('dbUSState', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogErrorMonit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbErrorMonit', models.CharField(max_length=500)),
                ('dbErrorTimeMonit', models.DateTimeField(auto_now_add=True)),
                ('dbErrorCodeMonit', models.CharField(max_length=500)),
            ],
        ),
    ]
